#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'countResponseTimeRegressions' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY responseTimes as parameter.
#

def countResponseTimeRegressions(responseTimes):
    if len(responseTimes) == 0:
        return 0
        
    count = 0    
    running_sum = responseTimes[0]
    
    for i in range(1, len(responseTimes)):
        average = running_sum / i
        if (responseTimes [i] > average):
            count+=1
        running_sum += responseTimes[i]
    return count
